//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVO_CSV
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public byte[] data { get; set; }
        public string auxiliar { get; set; }
        public int GRAFICO_id { get; set; }
    
        public virtual GRAFICO GRAFICO { get; set; }
    }
}
